### ISSUE TITLE
Unir Back-end e Front-end

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#101]
## Unir _Back-end_ e _Front-end_ 

**Tasks:**

- [x] Criar repositório contendo projeto do API Gateway
- [x] Definir rota para extração e interpretação de uma nota
   - [x] Fazer chamada correspondente no Front-end
- [x] Definir rota para envio de uma nota
   - [x] Fazer chamada corespondente no Front-end
- [x] Definir rota para listagem de notas
   - [x] Fazer chamada corespondente no Front-end

**Comment by Hargre** [comment]
**Tasks:**

- [ ] Criar repositório contendo projeto do API Gateway
- [ ] Definir rota para extração e interpretação de uma nota
   - [ ] Fazer chamada correspondente no Front-end
- [ ] Definir rota para envio de uma nota
   - [ ] Fazer chamada corespondente no Front-end
- [ ] Definir rota para listagem de notas
   - [ ] Fazer chamada corespondente no Front-end

**Comment by MarianaPicolo** [comment]
https://github.com/Kalkuli/2018.2-Kalkuli_Gateway
