### ISSUE TITLE
US34 - Acessar Página Principal

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#105]
## US34     

Eu, como **usuário do sistema**, desejo ter **acesso à pagina principal** do sistema para que eu possa ter **informações do _site_ e me cadastrar ou realizar _login_**.

***

### Critérios de Aceitação:   
- A tela principal deverá ser uma landing page.
- A tela deverá ter uma seção que mostra apenas o nome e o slogan do Kalkuli, além dos botões que linkam para outras seções da mesma página, um botão de login e outro de cadastro.
- A tela deverá ter uma seção que mostra informações sobre o Kalkuli e um botão de cadastrar a empresa, novamente.
- A tela deverá ter uma seção que mostra as funcionalidades principais do Kalkuli.
- A tela deve seguir o manual de identidade visual do projeto.

***   

### Tasks:
- [x] Implementar o esqueleto HTML seguindo o protótipo
- [x] Separar os arquivo scss para cada section da página
- [x] Junção da homepage com os componentes já existentes
- [x] Trocar o favicon e o título do site
- [x] Evolução da página com relação ao protótipo

**Comment by MarianaPicolo** [comment]
@clarissalimab:
- Critérios de Aceitação

@Jacoapolinario 
- _Tasks_

**Comment by clarissalimab** [comment]
Já coloquei os critérios de aceitação! 😺 

Observações:
- Os botões que precisam ser clicáveis são apenas os que levam às seções, já que as funcionalidades de log in e cadastro ainda não estão disponíveis.
- Os lorem ipsum do protótipo já devem estar substituídos por textos reais. Use a documentação do projeto para se inspirar no que escrever (o termo de abertura, o canvas e o documento de visão ajudam) 😋 

A tela é a primeira que aparece no protótipo: https://xd.adobe.com/view/db64571f-82f7-4449-53f2-e2c0db4b3bdb-ad55/

Quaisquer dúvidas sobre o que fazer e como fazer, é só dar um @ aqui que a gente ajuda!

**Comment by Jacoapolinario** [comment]
Acho que não vou saber explicar minhas duvidas escrevendo, Podemos marcar um hangouts mais tarde?

**Comment by MarianaPicolo** [comment]
Exponha suas dúvidas hoje na daily

**Comment by youssef-md** [comment]
As tasks iniciais combinadas com o @EsioFreitas já estão adicionadas.

**Comment by MarianaPicolo** [comment]
achei umas ideias legais de footer:

https://dribbble.com/shots/4740243-Agency-Footer;
https://dribbble.com/shots/4576839-This-is-the-End;
https://dribbble.com/shots/4949558-Footer-Lindholmen-se;
https://dribbble.com/shots/4896712-Footer-update
