### ISSUE TITLE
Hotfix - Corrigir Canvas

### ISSUE THREAD

**Issue by clarissalimab** [fga-eps-mds/2018.2-Kalkuli#130]
## Descrição da Issue
Realizar correções de acordo com o feedback recebido pelo coach e tornar a visibilidade do canvas mais agradável.

### Tasks:
- [x] Corrigir métricas-chave levando em conta o ROI
- [x] Corrigir aparência do canvas
- [x] Adicionar descrições sobre cada campo
