### ISSUE TITLE
US23 - Visualizar Lista de Relatórios

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#152]
## US23     

Eu, como **usuário do sistema**, desejo **visualizar uma lista de todos os relatórios salvos** para que eu possa **ter acesso a todos os relatórios**.

***

### Critérios de Aceitação:   
- O sistema deve exibir uma tela com uma lista de todos os relatórios gerados.
- No conteúdo de cada item da lista deve existir a data do relatório correspondente.
- Os itens da lista devem ser clicáveis, de forma que ao clicar em um deles, o usuário será levado para a visão detalhada do relatório correspondente.

***   

### Tasks:   
- [x]  Lista de todos os relatórios
- [x] Levar à visão detalhada dos relatórios
- [x] Criar um método GET no back, para pegar todos os relatórios
- [x] Comunicar Back com o Front
- [x] Exibir relatórios no front
- [x] Tratar erros

**Comment by MarianaPicolo** [comment]
@clarissalimab 
- Critérios de aceitação

@devsalula e @Phe0 
- _Tasks_

**Comment by clarissalimab** [comment]
Coloquei os critérios, se tiverem alguma dúvida é só falar! Bom trabalho ❤️
