### ISSUE TITLE
US24 - Visualizar um Relatório em Detalhes

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#153]
## US24      

Eu, como **usuário do sistema**, desejo **visualizar um relatório em detalhes** para que eu possa **ver os seus dados**.

***

### Critérios de Aceitação:   
- O relatório em detalhes deve ser visto através da seleção de um relatório na lista de todos os relatórios OU imediatamente após ser gerado (quando o usuário gerar o relatório ele deve ser direcionado pro relatório que foi gerado).
- O relatório deve conter a lista de todas as notas que estão contidas nele com o CNPJ, a data e o valor, o valor total das notas.
- Na parte superior do relatório deve ser inclusa uma espécie de título que dirá o intervalo das datas definidas para o relatório.

***   

### Tasks:    
- [x] Visualizar relatório
- [x] Visualizar campos do relatório
- [x] Botão com o intervalo de datas 
- [x] Tratar a exceção de um período sem notas
- [x] Deixar conteúdo dos relatórios bonitos (inserir labels e modificar a fonte)

**Comment by MarianaPicolo** [comment]
@clarissalimab 
- Critérios de aceitação

@devsalula e @Phe0 
- _Tasks_

**Comment by clarissalimab** [comment]
Coloquei os critérios, se tiverem alguma dúvida é só falar! Bom trabalho ❤️
