### ISSUE TITLE
Criar ambiente de homologação: Gateway

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#187]
### Tasks

- [x] Criar ambiente de homologação.
- [x] Mudar ambiente de produção.
- [x] Atualizar README para apresentar ambos os ambientes.

**Comment by MarianaPicolo** [comment]
@bernardohrl  tasks
