### ISSUE TITLE
Criar ambiente de homologação: Front-End

### ISSUE THREAD

**Issue by bernardohrl** [fga-eps-mds/2018.2-Kalkuli#196]
### Tasks:

- [x] Criar ambiente de homologação.
- [x] Atualizar README para apresentar ambos os ambientes.
- [x] Atualizar Guia de Deploy.
