### ISSUE TITLE
Hotfix - Adição de uma nota e o feedback da mesma

### ISSUE THREAD

**Issue by youssef-md** [fga-eps-mds/2018.2-Kalkuli#198]
## Descrição da Issue
Corrigir o armazenamento na store do envio de uma nota e o feedback de quando foi adicionada com sucesso.

### Tasks:
- [x] Corrigir o estilo do modal de quando foi enviada com sucesso
- [x] Tratar o armazenamento de uma nova nota na store
- [x] Refatoração do compartilhamento das receipts e tags via Redux

**Comment by youssef-md** [comment]
![photo5118858666550863898](https://user-images.githubusercontent.com/29265857/48091345-900d6e00-e1f0-11e8-9f1f-41b6769861c8.jpg)
Este erro que está presente ao acessar a listagem de todas as notas, e ocorre na tentativa de renderização de uma nota que não tem categoria, e será corrigido na de correção de fluxo da aplicação [issue 194](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/192) pois a categoria não é obrigatória. 
Portanto, enquanto a issue estiver em andamento sempre adicionem uma categoria ao inserir uma nova nota.
