### ISSUE TITLE
Criar Sistema de Migrations

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#214]
## Criar Sistema de _Migrations_
O sistema de migrations deve ser criado em todos os repoistórios que possui BD.

### Tasks

- [x] Criar migrations em Receipts
- [x] Criar migrations em Users
- [x] Criar migrations em Reports

**Comment by MarianaPicolo** [comment]
@bernardohrl _tasks_
