### ISSUE TITLE
Planejamento de Reuniões Semanais

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#29]
## Planejamento das Reuniões Semanais   

_Issue_ que mantém a rastreabilidade do que será abordado nos rituais e reuniões.   

Torna transparente o que será discutido para definir a próxima _sprint_. 

***    

- [Sprint 2](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-417827556)
- [Sprint 3](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-417966373)
- [Sprint 4](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-420445456)
- [Sprint 5](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-423369049)
- [Sprint 6](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-425291846)
- [Sprint 7](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-427342206)
- [Sprint 8](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-429435411)
- [Sprint 9](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-431466883)
- [Sprint 10](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-433591811)     
- [Sprint 11](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-435542559)   
- [Sprint 12](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-437523729)   
- [Sprint 13](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/29#issuecomment-439594185)

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 01/09/2018

EPS realizará o treinamento de prototipação (_Adobe XD_)

- _Review_ - Uma hora;  
   - MDS deverá apresentar o documento de visão (iniciado dia 29/08), e expor dúvidas que surgiram.
   - MDS deverá apresentar os protótipos de baixa fidelidade à equipe de EPS.
   - EPS apresentará a EAP até então acordada.

- Retrospectiva - Duas horas;    

- Pre Planejamento _Sprint_ 2 - Uma hora e quarenta e cinco minutos;   

|    MDS                        |                 EPS            |
|        :--:                   |          :---:                |
|  Protótipos de alta fidelidade(definir data antes do término da sprint) |   Finalizar TAP (definir data antes do término da sprint)|
|  Refinar o doc de visao       |   Subir _wiki_               |
|  definir identidade visual   |   Finalizar community profile           |
|  escrever documento de arquitetura   |   Definir politica de branches e commits    |
|  estudar js (apresentar um executável - resultados) |   Definir backlog do produto   |
|    |   escrever roadmaps dos papeis  |
|    |   escrever roadmap do produto |

**Comment by EsioFreitas** [comment]
Achei os padrões das notas fiscais 
http://app1.sefaz.mt.gov.br/Sistema/Legislacao/RegulamentoICMS.nsf/cc90333e16d28a8c0425736e0076800a/ea5e6fad3ae8c00104257391006c2984?OpenDocument

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 08/09/2018

Equipe de MDS terá provas durante a semana da _sprint_:    

| Data  | Disciplina  | Integrantes  |
|:-----------:|:----------:| :-----: |
 |  12/09 - Quarta |   MD II   | Esio, Dutra, Féo e Youssef
| 13/09 - Quinta |  EDA I   | Toda a Equipe  |  
 | 14/09 - Sexta |  MD I   | Saleh |    

> Considerar ao planejar _Sprint_ 3.

---

- _Review_ - Uma hora;  
   - [ ]     

- Retrospectiva - **Mudança de duração para uma hora**;    
  - Duração da retrospectiva anterior:   35min;

---

- Pré Planejamento _Sprint_ 3 -  **Mudança de duração para uma hora e trinta minutos**;
  - Duração do planejamento anterior:  1h;

|    MDS                        |                 EPS            |
|        :--:                   |          :---:                |
|    |   |

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 22/09/2018

- Quadro de conhecimento;   
- _Burndown_ de riscos;   
- SM e PM pontuarão histórias anteriores.
---

### _Review_ - Uma hora;      
   - [ ] MDS apresentará a [US13;](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/72)     
   - [ ] MDS apresentará a [US17](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/73);     
   - [ ] MDS apresentará a [US32](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/74);    
   - [ ] O _DevOps_ apresentará as [Integrações Contínuas](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/76)     
   - [ ] O _DevOps_ apresentará os [Bancos de Dados dos Serviços](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/80)    
   - [ ] A _Product Manager_ apresentará a [EAP refatorada](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/77);   
   - [ ] A _Product Manager_ apresentará a [Elaborar a Matriz de Avaliação de Valor](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/78);
   - [ ] A _Product Manager_ apresentará  [_Canvas_ refatorado](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/78); **_(Dívida)_**
   - [ ] _Scrum Master_ apresentará o [_Code Climate_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/75)      


### Retrospectiva - Uma hora;      
- Duração: Uma hora;   


### Pré Planejamento _Sprint_ 3    - Uma hora e trinta minutos       
- Duração:  40min

#### Histórias pre-planejadas    
> US15 - Filtrar notas  **13**;    
> US20 - Gerar um relatório de notas fiscais em um período selecionado. **8** ;     
> US14 - Visualizar uma nota detalhadamente para que eu possa verificar os dados. **8**     
**29 pts**    

|    MDS                        |                 EPS            |
|        :--:                   |          :---:                |
| Refatorar Artefatos | Deploy contínuo  ??pts|
| Correções de Bugs |  Reconstruir sprints anteriores| 
|Aumentar cobertura de testes||

==

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 29/09/2018 - _Sprint_ 6

- Quadro de conhecimento;   
- _Burndown_ de riscos;   
- Preparar apresentação para R1;
---

### _Review_ - Uma hora;      
- Duração: 1h;  

   - [ ] MDS apresentará a [US10](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/91)     
   - [ ] MDS apresentará a [US14](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/92);     
   - [ ] MDS apresentará a [US20](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/94);   
   - [ ] MDS apresentará o [Documento de Arquitetura Refatorado](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/96);   
   - [ ] A _Product Manager_ apresentará a [Matriz de Avaliação de Valor](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/78); **_(Dívida)_**   
   - [ ] A _Product Manager_ apresentará os [Resultados da Elicitação de Requisitos](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/102); 
   - [ ] A _Tech Leader_ apresentará os [Resultados das _Sprints_ Anteriores](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/98);   
   - [ ] O _DevOps_ apresentará os [_Deploys_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/97);    
   - [ ] O Arquiteto apresentará os resultados da [união entre _back-end_ e _front-end_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/97); 



### Retrospectiva - Uma hora;      
- Duração:  


### Pré Planejamento _Sprint_ 6    - Uma hora       
- Duração:   

#### Histórias pre-planejadas    
> US
> US
> US

|    MDS                        |                 EPS            |
|        :--:                   |          :---:                |
| Refatorar Identidade Visual |  |
|  |  | 
|  |  |

* doc planejamento sprint 6
* doc resultados sprint 5

==

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 06/10/2018 - _Sprint_ 7

- Quadro de conhecimento;   
- _Burndown_ de riscos;     
- Revisar as métricas de código;    
---

### _Review_ - Uma hora;      
- Duração: 1h;  

   - [ ] MDS apresentará a evolução da [US20](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/120)     
   - [ ] MDS apresentará a evolução da [US10](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/119);     
   - [ ] MDS apresentará a [evolução da identidade visual](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/121);   
   - [ ] MDS apresentará a [US34](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/105); **_(Dívida)_**    
   - [ ] O _DevOps_ apresentará os [deploys contínuos](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/97); **_(Dívida)_**    
   - [ ] A _Product Manager_ apresentará os [Resultados da Elicitação de Requisitos](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/102);    
   - [ ] O _DevOps_ apresentará os [_Deploys_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/97);    
   - [ ] O Arquiteto apresentará as [_releases_ do projeto](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/125); 


### Retrospectiva - Uma hora;      
- Duração:  1h


### Pré Planejamento _Sprint_ 6    - Uma hora       
- Duração: 50min   

#### Histórias Pre-planejadas    

> testar o front

|    MDS                        |                 EPS            |
|        :--:                   |          :---:                |
|   |   |
|  | | 
|  | |  
| |  |

* doc planejamento sprint 7
* doc resultados sprint 6

==

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 20/10/2018 - _Sprint_ 9

Equipe de MDS e EPS terá provas durante a semana da _sprint_:    

| Data  | Disciplina  | Integrantes  |
|:-----------:|:----------:| :-----: |
| 23/10 - Terça |  EDA I   | MDS |  
| 24/10 - Quarta |  MD II   | Esio, Dutra Féo e Youssef  |  
| 26/10 - Sexta |  DAS   | EPS  |  

> Considerar ao planejar _Sprint_ 9.        

- Quadro de conhecimento;   
- _Burndown_ de riscos;     
- Revisar as métricas de código;    
- Rotação de papeis;

---

### _Review_ - Uma hora;  
   - [ ] MDS apresentará a [US12 - Excluir Nota do Sistema](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/142);     
   - [ ] MDS apresentará a [US23 - Visualizar Lista de Relatórios](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/152);   
   - [ ] MDS apresentará a [US35 - Inserir Descrição e Título na Nota](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/151);   
   - [ ] MDS apresentará a [US24 - Visualizar um Relatório em Detalhes](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/153);       
   - [ ] MDS apresentará a [US33 - Gerar Relatório por Período Definido](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/126); **_(Dívida)_**    
   - [ ] O _DevOps_ apresentará a [migração do _deploy_ do serviço _extraction_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/155);        
   - [ ] A _Product Manager_ apresentará o [Plano de Projeto](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/156);    
   - [ ] Arquiteto apresentará o [_Serverless_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/157);            


### Retrospectiva  - Uma hora    
- Duração:     

### Pré Planejamento _Sprint_ 8    - Uma hora       
- Duração:     


#### Histórias Pré-Planejadas      

> US01 - Inserir o cadastro de uma empresa ao sistema - 13 
> US29 - Exportar relatório em .csv - 5   
> Modelo de maturidade de DevOps   

==      

> 
> divida EVM 8   
==    

|    MDS                        |                 EPS            |
|        :--:                   |          :---:                |
|   |  |

* doc planejamento sprint 9
* doc resultados sprint 6

==

**Comment by EsioFreitas** [comment]
## Planejamento da reunião de 20/10/2018 - _Sprint_ 10

> Considerar ao planejar _Sprint_ 10.        

- Quadro de conhecimento;   
- _Burndown_ de riscos;     
- Revisar as métricas de código;    
- Rotação de papeis;

---

### _Review_ - Uma hora;  
   - [ ] MDS apresentará a [US01 - Inserir o cadastro de uma empresa ao sistema](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/163);     
   - [ ] MDS apresentará a [US01 - Inserir o Cadastro de Uma Empresa no Sistema](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/163);   
   - [ ] MDS apresentará a [Melhorar Responsividade do Site](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/165); 
   - [ ] A _Product Manager_ apresentará o [Guia de Teste de Usabilidade](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/169);     
   - [ ] O _DevOps_, Arquiteto e Lucas Dutra apresentarão a [migração do _deploy_ do serviço _Interpretation_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/168);
   - [ ] O _DevOps_, Arquiteto e Lucas Dutra apresentarão a [migração do _deploy_ do serviço _Extraction_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/167);   
   - [ ] O _DevOps_, Arquiteto e Lucas Dutra apresentarão a [migração do _deploy_ do serviço _Gateway_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/166);        
   - [ ] O _Scrum_ _Master_ e _DevOps_ apresentarão a [atualização do _Code_ _Climate_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/170);   
- [ ] A _Scrum_ _Master_ apresentará o [EVM](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/124);   
- [ ] A _Product Manager_  apresentará a [ correções a EAP](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/109);   

### Retrospectiva   
- Duração: 1 hora

### Pré Planejamento _Sprint_ 11           
- Duração: 1 hora   

#### Histórias Pré-Planejadas      

|    MDS                        |                 EPS            |
|        :--:                   |          :---:                |
|   |  |

* doc planejamento sprint 10
* doc resultados da sprint 9

==

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 03/11/2018 - _Sprint_ 11

Equipe de MDS terá provas durante a semana da _sprint_:    


| Data  | Disciplina  | Integrantes  |
|:-----------:|:----------:| :-----: |
| 07/10 - Quarta |  MD I   | Saleh (MDS)|  
     
> Considerar ao planejar _Sprint_ 11        

- Quadro de conhecimento;   
- _Burndown_ de riscos;     
- Revisar as métricas de código;    
- Rotação de papeis;

---

### _Review_ - Uma hora;  
 - [ ] MDS apresentará a [US18 - Inserir Categoria em Nota](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/174);   
- [ ] MDS apresentará a [US09 - Realizar _Login_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/163);   
- [ ] MDS apresentará a [US01 - Inserir o Cadastro de Uma Empresa no Sistema](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/163); **(dívida)**  
- [ ] O Arquiteto apresentará o [Sistema de Background _Tasks_ para a Extração](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/177);      
- [ ] O _DevOps_ apresentrá o [Modelo de Maturidade _DevOps_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/176);     
- [ ] A _Product Manager_ apresentará o [Guia de Teste de Usabilidade](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/169);  **(dívida)**     
- [ ] A _Scrum_ _Master_ apresentará o [EVM](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/124);     **(dívida)**      

### Retrospectiva   
- Duração: 1 hora

### Pré Planejamento _Sprint_ 10           
- Duração: 1 hora   

#### Histórias Pré-Planejadas      
##### Dívidas

##### Histórias Planejadas
Melhorar extração
Melhorar interpretação
  

Pontos de dívida: xx   
Pontos planejados: xx  
**Pontos totais: xx**    

* doc planejamento sprint 11
* doc resultados da sprint 10

==

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 10/11/2018 - _Sprint_ 12

Equipe de MDS terá provas durante a semana da _sprint_:    


| Data  | Disciplina  | Integrantes  |
|:-----------:|:----------:| :-----: |
| 16/11 - Sexta-feira |  PED   | Saleh (MDS)|  
     
> Considerar ao planejar _Sprint_ 12        

- Quadro de conhecimento;   
- _Burndown_ de riscos;     
- Revisar as métricas de código;    
- Rotação de papeis;

---

### _Review_ - Uma hora;     
- O _DevOps_ apresentará os ambientes de homologação:
    -  [ ] [Serviço de Interpretação](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/186);
    -  [ ] [_Gateway_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/187);   
    -  [ ] [Serviço de Usuários](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/188);
    -  [ ] [Serviço de Notas](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/189);
    -  [ ] [Serviço de Relatórios](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/190);
    -  [ ] [Serviço de Exportação](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/191);
    -  [ ] [_Front-end_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/196);
- [ ] MDS apresentará a [US15 - Filtrar Notas por Título e Descrição](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/194);   
- [ ] MDS apresentará a [US37 - Criar Categorias](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/195);   
- [ ] MDS apresentará a [US09 - Realizar _Login_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/163); **(dívida)**    
- [ ] MDS apresentará a [US37 - Criar Categorias](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/195);   
- [ ] MDS apresentará a [Correção os Fluxos da Aplicação](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/192);   
- [ ] O Arquiteto apresentará a [Refatoração do Serviço de Extração: Corrigir o _Deploy_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/185) ;      
- [ ] A _Product Manager_ apresentará o [_Backlog Atualizado_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/193);   
- [ ] EPS apresentará a [Refatoração do Serviço de Extração: Refatorar Código](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/184)    

### Retrospectiva   
- Duração: 1 hora

### Pré Planejamento _Sprint_ 10           
- Duração: 1 hora   

#### Histórias Pré-Planejadas      
##### Dívidas   

##### Histórias Planejadas     

Alterar senha
Recuperar senha
Excluir um relatório da lista de relatórios
Gerar PDF de relatórios ?
Gerar gráficos totais 
Testes de usabilidade ?


Pontos de dívida: xx     
Pontos planejados: xx  
**Pontos totais: xx*    

* doc planejamento sprint 12
* doc resultados da sprint 11

==

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 17/11/2018 - _Sprint_ 13

Equipe de MDS terá provas durante a semana da _sprint_:    


| Data  | Disciplina  | Integrantes  |
|:-----------:|:----------:| :-----: |
|  |    |  |  
     
> Considerar ao planejar _Sprint_ 13        

- Quadro de conhecimento;        
- Revisar as métricas de código;    

---

### _Review_ - Uma hora;     
- O _DevOps_ apresentará os ambientes de homologação:
    -  [x] [Serviço de Interpretação](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/186);
    -  [x] [_Gateway_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/187);   
    -  [x] [Serviço de Usuários](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/188);
    -  [x] [Serviço de Notas](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/189);
    -  [x] [Serviço de Relatórios](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/190);
    -  [x] [Serviço de Exportação](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/191);
    -  [x] [_Front-end_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/196);

- [ ] MDS apresentará a [US25 - Apagar Relatório](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/202);   
- [ ] MDS apresentará a [US38 - Editar Nota](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/203);   
- [ ] MDS apresentará a [US22 - Gerar Relatório por Categoria](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/204);     
- [ ] MDS apresentará a [US27 - Gerar Gráfico de Gastos Totais ]( https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/206) 
- [ ] MDS apresentará a [US36 - Associar Notas à Empresa ](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/205 )
- [ ] MDS apresentará a [Correção dos Fluxos da Aplicação](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/192);   **(dívida)**   
 
- [x] O Arquiteto apresentará a [Refatoração do Serviço de Extração: Corrigir o _Deploy_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/185) ;      
- [x] A _Product Manager_ apresentará o [_Backlog Atualizado_](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/193);   
- [x] EPS apresentará a [Refatoração do Serviço de Extração: Refatorar Código](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/184)    

### Retrospectiva   
- Duração: 1 hora

### Pré Planejamento _Sprint_ 10           
- Duração: 1 hora   

#### Histórias Pré-Planejadas      
##### Dívidas   
EVM 8

##### Histórias Planejadas     

- Fazer releases   
- EPS Testes de usabilidade (escrever cenarios e testar) 13    

---

US25 Excluir relatorio 2 (esio + dutra )
US38 Editar nota 3 (esio + dutra)    
US22 Filtrar por categoria 5 (esio + youssef)  
US36 Associar nota ao usuario 13 (dutra + felipe)
US27 Gerar gráficos totais 8 (feo + saleh )        
Aumentar a cobertura do front 13 (feo + youssef ) 

- ATUALIZAR GUIA DO DEPLOY 3   
- SISTEMA DE TROCA DE AMBIENTES AUTOMATIZADO 5 (saleh + bernardo)   
- SCRIPT DE POPULAR BD 1  


Pontos de dívida: 8     
Pontos planejados: 66  
**Pontos totais: 74**    

* doc planejamento sprint 12
* doc resultados da sprint 11

==

**Comment by MarianaPicolo** [comment]
## Planejamento da reunião de 24/11/2018 - Pré _Release_  

- Quadro de conhecimento final;        
- _Post mortem_  

---

### _Review_ - Uma hora;     

- [ ] MDS apresentará a [US39 - Fazer Logout](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/220);   
- [ ] MDS apresentará a [US38 - Editar Nota](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/203); **(dívida)**    
- [ ] MDS apresentará a [US22 - Gerar Relatório por Categoria](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/204);   **(dívida)**       
- [ ] MDS apresentará a [US27 - Gerar Gráfico de Gastos Totais ]( https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/206)   **(dívida)**   
- [ ] MDS apresentará a [US36 - Associar Notas à Empresa ](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/205 )  **(dívida)**   
- [ ] MDS apresentará a [cobertura de testes do _front-end_ ](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/207);   
- [ ] MDS apresentará o [Documento de Arquitetura Atualizado](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/219);    
- [ ] MDS apresentará a [melhora da responsividade](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/221);     
- [ ] MDS apresentará os [testes no front-end atualizados](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/223);    
- [ ] DevOps apresentará o [modelo de maturidade atualizado](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/222);    
- [ ] MDS apresentará o [serviço de exportação atualizado](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/225);     
- [ ] MDS apresentará o [serviço de relatórios atualizado](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/224);     
- [ ] A _Product Manager_ apresentará os [testes de usabilidade](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/211);   



### Retrospectiva Final (Esboço do _Post Mortem_)  
- Duração: 1 hora



* doc resultados da sprint 13 

==

**Comment by MarianaPicolo** [comment]
@MarianaPicolo Tá acabando, lindos!
<3
