### ISSUE TITLE
US19 - Fazer o upload de uma nota fiscal

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#46]
# US19 - Fazer o _upload_ de uma nota fiscal

## US19   
Eu, como **usuário do sistema**, desejo **fazer o upload de uma nota fiscal** para que os dados das notas fiscais fiquem salvos no sistema.

***

### Critérios de Aceitação:
- O sistema deve receber um arquivo em PDF de uma nota fiscal.
- O sistema deverá checar se o arquivo submetido está em formato PDF ou não.
- O sistema deve extrair o texto do PDF e printar na tela OU gerar um json.
- Este recurso deve interagir com o front-end desta funcionalidade. (US31 #48).

***   

### Tasks:
- [ ] Receber o arquivo do front-end 
- [x] Validar o arquivo recebido
- [x] Converter o arquivo para imagem
- [x] Extração de texto com o PyTesseract
- [x] Retornar o texto extraído

**Comment by Hargre** [comment]
Umas notas sobre essa issue:
* Pelo menos por hora, vamos usar o pytesseract. Pra isso precisa converter o PDF pra imagem antes. Todos os pacotes necessários já estão instalados no container.
* Com a imagem a gente consegue rodar o OpenCV pra tentar aumentar a qualidade da extração. Esse eu esqueci de botar, heh. Mais tarde subo lá e aí é só buildar o container de novo.

**Comment by Hargre** [comment]
Tudo arrumado agora!

**Comment by devsalula** [comment]
Repositório com um programa que faz extração de texto. 
https://github.com/devsalula/extrator-pdf

**Comment by Hargre** [comment]
Guias de OpenCV pra tratamento de imagem escaneada:

https://markhollow.com/2017/02/09/programmatically-cleaning-document-scans/
https://markhollow.com/2017/03/04/programmatically-cleaning-document-scans-part-2/

**Comment by Hargre** [comment]
O teste que eu tinha feito tá aqui:
https://github.com/Hargre/flask-ocr-sample
Tá no OCRmyPDF, mas a lógica é parecida. Só o código que tá bem bagunçado :sweat_smile:

**Comment by lucasdutraf** [comment]
Achei um repositório que tem alguns exemplos de testes usando flask, pode ser interessante:
Se encontra no README.md
https://github.com/mjhea0/flaskr-tdd#test-driven-development

**Comment by Hargre** [comment]
Mais sobre testes em Flask: 
https://testdriven.io/part-one-test-setup
http://flask.pocoo.org/docs/1.0/testing/

**Comment by devsalula** [comment]
Sobre Blueprints

**Comment by devsalula** [comment]
@Hargre, como podemos tratar uma entrada de arquivo diferente do esperado por parte do usuário?

**Comment by lucasdutraf** [comment]
Encontramos essa parte da documentação que descreve bem uma das funcionalidades que temos que implementar:
http://flask.pocoo.org/docs/0.12/patterns/fileuploads/

**Comment by lucasdutraf** [comment]
@clarissalimab é esperado que o arquivo enviado seja salvo no banco de dados pra essa sprint? Pois estamos salvando o arquivo recebido localmente, porém pode facilmente ser adaptado

**Comment by clarissalimab** [comment]
@lucasdutraf Não precisa por enquanto.

**Comment by lucasdutraf** [comment]
Esse link pode ser bem útil, mostra padrões para status e erros para serem devolvidos por JSON
https://cloud.google.com/storage/docs/json_api/v1/status-codes
