### ISSUE TITLE
US31 - Criar interface gráfica para realizar upload de notas fiscais

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#48]
## US31   

Eu, como _usuário do sistema_, desejo _utilizar uma interface gráfica_ para realizar o _upload de notas fiscais_.

***

### Critérios de Aceitação:
- A tela deve conter um botão que permita que o usuário busque um arquivo explorando as pastas do computador.
- A tela deve conter um recurso que permita que o usuário adicione um PDF através do recurso drag & drop.
- A tela deve seguir o manual de identidade visual do projeto. 
- As interações desta tela devem estar conectadas com o back-end desta funcionalidade. (US19 #46).

***   

### Tasks:
- [x] Aprovar o protótipo final dos designers.
- [x] Implementar o botão para que o usuário busque o arquivo desejado.
- [x] Implementar a estrutura da página utilizando a biblioteca React JS.
- [x] Implementar as folhas de estilo utilizando o Sass como preprocessador de CSS.
- [x] Adicionar a área de drag & drop para o arquivo desejado.
- [x] Desenvolver o início do upload do arquivo selecionado.

**Comment by clarissalimab** [comment]
@youssef-md @Jacoapolinario já coloquei os critérios de aceitação. Por favor, coloquem as tasks. 😃

**Comment by Phe0** [comment]
Protótipo de alta fidelidade da seção de adicionar notas : 
https://xd.adobe.com/view/db64571f-82f7-4449-53f2-e2c0db4b3bdb-ad55/
