### ISSUE TITLE
US16 -  Pesquisar o padrão de notas fiscais

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#49]
## US16   
Eu, como _desenvolvedor_, desejo **entender o padrão de notas fiscais** para que eu aprenda **como interpretar suas informações**.   

***

### Critérios de Aceitação:
Como história de estudo, deseja-se que o resultado gerado a partir dela seja um estudo mais palpável a respeito do padrão das notas fiscais. Assim, se espera que tenhamos informações reunidas (e repassadas para o time) suficientes para sermos capazes de classificar os dados de uma nota fiscal extraída.

***   

### Tasks:
- [x] Pesquisar os dados 
- [x] Validar os dados 
- [x] Registrar os dados

**Comment by Hargre** [comment]
Algo que talvez ajude pra parte de interpretação: 
O Rasa (http://www.rasa.com/) é um software _open-source_ pra construção de bots, mas tem ferramentas de processamento de linguagem que talvez ajudem a gente, especialmente essa parte aqui: http://www.rasa.com/docs/nlu/master/entities/. 

Tem inclusive uma issue de alguém querendo fazer algo bem parecido com o nosso contexto: https://github.com/RasaHQ/rasa_nlu/issues/578. A gente poderia abrir uma issue lá também, pra ver se esse serviço deles poderia ser adaptável pro nosso caso.

Créditos pro @devsalula que tinha mencionado o Rasa na reunião :stuck_out_tongue_winking_eye:

**Comment by EsioFreitas** [comment]
Time, tivemos um equivoco em relação a nota fiscal, cupom fiscal e DANFE. Estou pesquisando melhor sobre e como isso impacta na aplicação. Na daily de hoje eu explico melhor. 
Segue alguns links que explica melhor o que eu estou dizendo. 

https://sistemasoma.com.br/blog/gestao-financeira/diferencas-entre-coupon-fiscal-nota-fiscal-e-recibo
https://www.asaas.com/blog/comprovante-de-pagamento-qual-e-a-importancia/
https://jus.com.br/duvidas/50225/nota-fiscal-ou-recibo-de-pagamento-sonegacao-fiscal
http://www.atimosoftware.com.br/danfe-nao-e-a-mesma-coisa-que-nota-fiscal-eletronica/

**Comment by clarissalimab** [comment]
@EsioFreitas @Phe0 já coloquei os critérios de aceitação. Por favor, coloquem as tasks. 😃

Sugestão: façam um documento com as informações úteis/ importantes que vocês encontrarem. Na próxima reunião gostaríamos que vocês pudessem repassar para o time tudo que encontraram para evitar retrabalho de novas pesquisas.

**Comment by Phe0** [comment]
https://www.kcms.com.br/blog/cupom-fiscal-e-nota-fiscal-entenda-a-diferenca/

**Comment by Hargre** [comment]
Mais um artigo interessante sobre extração: https://dzone.com/articles/using-ocr-for-receipt-recognition 
É mais técnico, um bocadinho complexo. Mas a gente pode dar uma olhada nas ideias de forma geral.

**Comment by EsioFreitas** [comment]
Segue link do documento feito para apresentação no sábado (15/07). 
PS.: Contem spoilers 

https://docs.google.com/presentation/d/1GEtSYPaH5CdNlBbwu52KV0vSeFT5Grj_EeeVi2r6APs/edit?usp=sharing
