### ISSUE TITLE
US17 - Interpretar Dados de Notas Fiscais

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#73]
## US17     

Eu, como **usuário do sistema**, desejo que uma **nota fiscal submetida seja interpretada** para que seus **dados sejam disponibilizados** de uma forma mais acessível. 

***

### Critérios de Aceitação:   
* O conteúdo extraído das notas deve ser retornado de forma que as informações obtidas estejam classificadas (nome, valor...)

***   

### Tasks:
- [x] -  Receber texto a ser interpretado
- [x] -  Criar regex para extrair o preço
- [x] -  Criar regex para extrair a data
- [x] - Criar regex para extrair o cnpj
- [x] -  Converter e retornar JSON
- [x] - Testes

**Comment by clarissalimab** [comment]
Coloquei os critérios! 😋
