### ISSUE TITLE
US32 - Armazenar Notas Fiscais no Sistema

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#74]
## US32     

Eu, como **usuário do sistema**, desejo que os **dados da nota fiscal fiquem armazenados no sistema** para que eu possa **gerar relatórios a partir delas e consultá-las**.

***

### Critérios de Aceitação:   
* Depois de selecionar um arquivo de nota fiscal, o sistema deverá habilitar um botão de "Extrair dados" para que o usuário envie a nota para extração;
* Depois da extração dos dados, o sistema deve exibir uma tela de confirmação com os dados extraídos e a imagem da nota com a opção de enviar nota ao sistema;
* Os dados extraídos e a imagem da nota devem ficar armazenados no sistema (localmente, por hora);
* Ao enviar a nota para o sistema, o usuário deverá receber uma confirmação de que a nota foi submetida com sucesso.

***   

### Tasks:
- [x] - Ação de redirecionamento da tela de envio de arquivo para a tela de comparar dados (rotas)
- [x] - Componente de carregamento para reutilização na aplicação 
- [x] - Deixar os dados da nota editável
- [x] - Renderizar o arquivo PDF 
- [x] - Ao confirmar os dados, os mesmos serão enviados ao banco de dados
- [x] - Exibir na tela uma confirmação de submissão dos dados da nota

**Comment by clarissalimab** [comment]
Coloquei os critérios! 😋  Seria legal se vocês conseguissem colocar uma barra de progresso e algum tipo de spinner nos momentos em que o usuário espera por resposta do sistema para que ele tenha algum feedback, mas não sei qual o nível de dificuldade disso por enquanto, por isso não coloquei ainda nos critérios.

**Comment by Phe0** [comment]
Eu e @youssef-md adicionamos as Tasks

**Comment by Phe0** [comment]
Spinners: 
https://loading.io/css/

**Comment by Phe0** [comment]
Sobre leitura e escrita de arquivos json: 
https://youtu.be/9ql0uA6ziJs

**Comment by youssef-md** [comment]
Funcionamento e implementação de rotas em React : https://www.youtube.com/watch?v=QUz3k2O3ZJU

**Comment by youssef-md** [comment]
Bibliotecas para fazer o preview do pdf: https://mozilla.github.io/pdf.js/ , https://www.npmjs.com/package/react-pdf
