### ISSUE TITLE
Elaborar a Matriz de Avaliação de Valor

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#78]
# Elaborar a Matriz de Avaliação de Valor
### Tasks
- [x] Pesquisar por possíveis concorrentes
- [x] Verificar atributos do produto
- [x] Fazer comparações de cada ponto levantado no tópico anterior
- [x] Elaborar matriz

**Comment by clarissalimab** [comment]
Espresso: https://www.espressoapp.com.br/
Novoto: https://www.novoto.com.br/
ContaAzul: https://contaazul.com/
