### ISSUE TITLE
US10 - Editar Envio de Uma Nota

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#91]
## US10     

Eu, como **usuário do sistema**, desejo poder **editar o envio de uma nota fiscal** para que eu possa **corrigir dados incorretos** na extração dos dados da nota.
***

### Critérios de Aceitação:   
- No momento em que uma nota fiscal é submetida, na tela de confirmar os dados, deve ser exibido o PDF da nota submetida ao lado dos dados extraídos em forma de texto.
- Os textos extraídos devem poder ser alterados através de um campo editável. É importante deixar explícito ao usuário que o campo é editável.
- As telas devem seguir o manual de identidade visual do projeto. 

***   

### Tasks:
- [x] Refatorar a tela de acordo com ID visual;
   - [x] Definir o tamanho da div interna (dentro do modal), para que possa ser reajustada em diferentes tamanhos de tela.
   - [x] Tamanho dos botões (de acordo com o protótipo)
   - [x] Ajustar o recibo para que tenha mais espaço para caber os botões
- [x] Botão destinado para a edição dos campos;
   - [x] Definir ícone para o botão
- [x] Tornar os campos editáveis ou não por meio do botão;
- [x] Estilização coerente com os campos dependendo do seu estado;
- [x] Preview do PDF
- [x] Visualizar o PDF ao lado da nota

**Comment by MarianaPicolo** [comment]
@clarissalimab:
 - Critérios de aceitação

@youssef-md, @lucasdutraf e @EsioFreitas 
- Tasks

**Comment by clarissalimab** [comment]
Já coloquei os critérios de aceitação! 😺

**Comment by EsioFreitas** [comment]
Tasks adicionadas

**Comment by lucasdutraf** [comment]
Qual o back-end presente nessa issue? Não ficou muito claro pra mim

**Comment by MarianaPicolo** [comment]
Essa história ainda não faz conexão com o backend, vou retirar a label

**Comment by youssef-md** [comment]
Tasks atualizadas

**Comment by lucasdutraf** [comment]
@EsioFreitas @youssef-md e eu dividimos as tasks antes colocadas em menores partes! :+1:
