### ISSUE TITLE
US20 - Gerar Relatório de Notas Fiscais

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#94]
## US20   

Eu, como **usuário do sistema**, desejo **gerar um relatório de notas fiscais** para que eu possa ter uma **lista de todos os gastos**.

***

### Critérios de Aceitação:   
- A partir da tela de lista de notas fiscais, o usuário deve ter acesso a uma opção de gerar relatórios.
- O relatório deve conter uma lista de todas as notas submetidas.
- Cada item da lista deve mostrar, por hora, o CNPJ, a data e o valor da nota.
- No fim do relatório é preciso mostrar a soma do valor de todas as notas que estão na lista (o valor total).
- A história deve seguir o manual de identidade visual do projeto.

***   

### Tasks:
- [x] -  Criar método post para salvar o relatório no banco
- [x] -  Somar valores de cada nota 
- [x] -  Criar tela da dashboard
- [x] -  Criar área de relatório 
- [x] -  Criar tela de relatórios 
- [x] -  Receber arquivo JSON no back

**Comment by MarianaPicolo** [comment]
@clarissalimab:
- Critérios de aceitação

@Phe0  e @devsalula 
- Tasks

**Comment by clarissalimab** [comment]
Já coloquei os critérios de aceitação! 😺

**Comment by Phe0** [comment]
Atualizamos o protótipo para conter essa história:

https://xd.adobe.com/view/db64571f-82f7-4449-53f2-e2c0db4b3bdb-ad55/

**Comment by Phe0** [comment]
Tasks já foram criadas

**Comment by Phe0** [comment]
Pesquisa de Notas por data usando flask :
https://stackoverflow.com/questions/40448041/how-to-get-query-a-certain-period-of-datetime-in-flask-sqlalchemy

http://flask-sqlalchemy.pocoo.org/2.3/queries/
